# Generated by Django 4.2 on 2023-04-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.DateField(max_length=30, null=True, verbose_name='phone number'),
        ),
    ]
