# Generated by Django 4.2 on 2023-05-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_restaurant_owner',
            field=models.BooleanField(default=False, verbose_name='restaurant owner'),
        ),
    ]
