# Generated by Django 4.2 on 2023-05-20 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_restaurant_owners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant_owners',
            new_name='Restaurant_owner',
        ),
    ]
