# Generated by Django 4.2 on 2023-05-20 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_restaurant_owners_restaurant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_restaurant_owner',
        ),
    ]
