# Generated by Django 4.2 on 2023-04-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
