# Generated by Django 4.2 on 2023-04-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_customer_id_review_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.CharField(default='', max_length=1),
        ),
    ]
